small_division_teams = [
    "Barelang FC",
    "Berlin United",
    "Blenders FC",
    "Bold Hearts",
    "CAU Mountain&Sea",
    "Colmillos ITAM",
    "EWS Bascorro",
    "GeoHBots",
    "Hamburg Bit-Bots",
    "HUST-HRT",
    "I-Kid",
    "ICHIRO ITS",
    "Invic",
    "ITAndroids",
    "KHUBER",
    "Mountain",
    "NUbots",
    "RO:BIT",
    "SABANA HERONS",
    "WF Wolves",
    "ZJUDancer",
]